//> using scala "2.13"
//> using lib "io.get-coursier::coursier:2.0.16"
//> using lib "org.typelevel::cats-effect:3.3.1"
//> using lib "org.typelevel::cats-effect-std:3.3.1"
//> using lib "com.monovore::decline-effect::2.2.0"
